### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by znowden** [coryhouse/react-slingshot#116]
After downloading react-slingshot and calling "npm install" I get this error:

    313437 info install react-slingshot@3.0.1
    313438 info postinstall react-slingshot@3.0.1
    313439 info prepublish react-slingshot@3.0.1
    313440 verbose validateInstall loading C:\Users\znowden\Desktop\react-slingshot\package.json for validation
    313441 verbose stack Error: The package react@15.0.1 does not satisfy its siblings' peerDependencies requirements!
    313441 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:125:32
    313441 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:268:7
    313441 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:142:5
    313441 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
    313441 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
    313441 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
    313441 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
    313441 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
    313441 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
    313441 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
    313442 verbose cwd C:\Users\znowden\Desktop\react-slingshot
    313443 error Windows_NT 10.0.10586
    313444 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
    313445 error node v4.4.3
    313446 error npm  v2.15.1
    313447 error code EPEERINVALID
    313448 error peerinvalid The package react@15.0.1 does not satisfy its siblings' peerDependencies requirements!
    313448 error peerinvalid Peer react-dom@15.0.1 wants react@^15.0.1
    313448 error peerinvalid Peer react-redux@4.4.0 wants react@^0.14.0
    313448 error peerinvalid Peer react-addons-test-utils@15.0.1 wants react@^15.0.1
    313448 error peerinvalid Peer enzyme@2.2.0 wants react@0.13.x || 0.14.x || 15.* || ^15.0.0-rc
    313449 verbose exit [ 1, true ]

Then when calling "npm start" I get this error from tools\testSetup.js:26:1 :

    Error: Cannot find module 'babel-register'

VC++ components and Python 2.7 are installed as instructed.

**Comment by piotrkaczmarek** [comment]
About that second issue I'm convinced that you got this error after calling `npm test` (`npm start` should not even try to load testSetup). I had the same problem. Try solving it by running:
````bash
npm install babel-register --save-dev
````

I've just submitted a PR that fixes it https://github.com/coryhouse/react-slingshot/pull/117 .

**Comment by coryhouse** [comment]
Fixed! Thanks for the PR!

**Comment by znowden** [comment]
The PR did not fix the issue and I did not run npm test. I cloned the repo, entered "npm install" then "npm start". Let me know if you need more details, this is a fresh clone on a reasonably clean machine so would expect to see more reports of this in the near future.

**Comment by coryhouse** [comment]
Odd, about to head out to dinner. I'll give this a look tonight.

**Comment by coryhouse** [comment]
@znowden It's installing from scratch just fine on my Windows machine. Did you complete the setup steps listed in the docs? 

Can you provide the following?
1. Windows version
2. What command line you're using on Windows
3. npm version
4. node version

**Comment by czaas** [comment]
Under dependencies update react-redux 4.4.0 in the package.json to 4.4.1

http://stackoverflow.com/questions/35890730/react-15-not-compatible-with-react-redux

**Comment by znowden** [comment]
Thanks, upgrading react-redux to 4.4.1 worked.

**Comment by coryhouse** [comment]
Great to hear! Dependencies updated.
