### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by gitlovenotwar** [coryhouse/react-slingshot#170]
Node version:
6.2.0

npm version:
3.9.2

Operating system:
windows 7

Command line used:
npm run build

Steps to reproduce:
All test were passed, but running "npm run build" or "npm run prebuild" throws the error and it can build the files. http://take.ms/qXh6D

**Comment by coryhouse** [comment]
Move the project to a directory that doesn't contain a slash. That should fix it.

**Comment by coryhouse** [comment]
Actually, after looking again, it appears the path you're running in doesn't contain spaces. I suggest downgrading to Node 5.11.1. Node 6 has issues on some Windows machines.

**Comment by gitlovenotwar** [comment]
After downgrading to node 5.11.1, it's still having the same error.

**Comment by gitlovenotwar** [comment]
even the most recommended version of node 4.4.5, throws the same error

**Comment by coryhouse** [comment]
Why are you running this project from the xampp folder? Try running this
from a different directory. Make sure there are no spaces in the path.
Also, try running just the lint task. Does it fail? If so, with what?

**Comment by gitlovenotwar** [comment]
It's not running on xampp, I just happen to place all my project into one folder, which is in xampp :) Also, after running lint, it throws the same error. So, I guess the linting gives this error.

**Comment by coryhouse** [comment]
@gitlovenotwar Can you please share your solution so I can try to reproduce?
